/**
 * Registra globalmente los íconos de Ant Design que usa SIGAM,
 * para poder escribir <UserOutlined /> en cualquier plantilla.
 */
import {
    AppstoreOutlined,
    ArrowLeftOutlined,
    BarChartOutlined,
    BellOutlined,
    BulbOutlined,
    CalendarOutlined,
    CarOutlined,
    CheckCircleOutlined,
    ClockCircleOutlined,
    CloseOutlined,
    DashboardOutlined,
    DeleteOutlined,
    DownloadOutlined,
    DownOutlined,
    EditOutlined,
    EllipsisOutlined,
    EnvironmentOutlined,
    ExclamationCircleOutlined,
    EyeOutlined,
    EyeInvisibleOutlined,
    FileTextOutlined,
    FilterOutlined,
    FormOutlined,
    HistoryOutlined,
    InboxOutlined,
    LockOutlined,
    LoginOutlined,
    LogoutOutlined,
    MailOutlined,
    MenuOutlined,
    PaperClipOutlined,
    PlusOutlined,
    PrinterOutlined,
    QrcodeOutlined,
    SafetyOutlined,
    SafetyCertificateOutlined,
    SaveOutlined,
    SearchOutlined,
    SettingOutlined,
    ShopOutlined,
    SwapOutlined,
    TeamOutlined,
    ToolOutlined,
    UserOutlined,
    WarningOutlined,
} from '@ant-design/icons-vue';

const iconos = {
    AppstoreOutlined,
    ArrowLeftOutlined,
    BarChartOutlined,
    BellOutlined,
    BulbOutlined,
    CalendarOutlined,
    CarOutlined,
    CheckCircleOutlined,
    ClockCircleOutlined,
    CloseOutlined,
    DashboardOutlined,
    DeleteOutlined,
    DownloadOutlined,
    DownOutlined,
    EditOutlined,
    EllipsisOutlined,
    EnvironmentOutlined,
    ExclamationCircleOutlined,
    EyeOutlined,
    EyeInvisibleOutlined,
    FileTextOutlined,
    FilterOutlined,
    FormOutlined,
    HistoryOutlined,
    InboxOutlined,
    LockOutlined,
    LoginOutlined,
    LogoutOutlined,
    MailOutlined,
    MenuOutlined,
    PaperClipOutlined,
    PlusOutlined,
    PrinterOutlined,
    QrcodeOutlined,
    SafetyOutlined,
    SafetyCertificateOutlined,
    SaveOutlined,
    SearchOutlined,
    SettingOutlined,
    ShopOutlined,
    SwapOutlined,
    TeamOutlined,
    ToolOutlined,
    UserOutlined,
    WarningOutlined,
};

export default {
    install(app) {
        Object.entries(iconos).forEach(([nombre, componente]) => {
            app.component(nombre, componente);
        });
    },
};
